### ISSUE TITLE
Lists in Tracim should have a hover color lighter

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2673]
## Bug description & symptom

Lists in Tracim hover is a dark brown (or tracim main color). But this color is too dark and the text isn't readable. By the way, if the tracim main color is to light or too dark, it's not adapted.

## Expected

Lists hover could be a light grey. We need to set it as a fixed color.
All lists in Tracim should have the same color

## Screenshots

Current hover action in workspace contents:
![brown_hover](https://user-images.githubusercontent.com/50453784/73923333-00f77600-48cb-11ea-9991-4e803ffbe1ff.gif)

**Changes:**

Recent activity in Dashboard:
![Overview1](https://user-images.githubusercontent.com/31687635/79866536-39dcbc80-83dd-11ea-9de7-7e358321e0f3.gif)

Member list in Dashboard:
![Overview2](https://user-images.githubusercontent.com/31687635/79866563-3f3a0700-83dd-11ea-946b-9def7521253d.gif)

Workspace contents:
![Overview3](https://user-images.githubusercontent.com/31687635/79866596-4e20b980-83dd-11ea-8ab9-982fca6e9b41.gif)

**Comment by metzgegu** [comment]
Currently the Tracim primary color is applied to a lot of content when `hover` (btn extended action, MemberList...) , so if we change it in list of contents we need to change it everywhere in Tracim.

**Comment by Skylsmoi** [comment]
@metzgegu the idea is to change the mouseover color to something easier to read like in the provided gif
We won't change the primary color

Propositions of solutions:
- use a fixed hover color (as seen in the gif above)
- use opacity to have a mouse hover less opaque
- don't use background color on hover and use bordercolor

**Comment by metzgegu** [comment]
Okay,
- Use borderColor on hover is not enough consistent with current buttons hover style in Tracim
- Use opacity to have a mouse hover less opaque could be a great solution see preview with current primary color with opacity `0.9` : 

![LightgreyHover](https://user-images.githubusercontent.com/31687635/79767384-8e266480-8329-11ea-8880-4e2e3cdceeab.gif)

Or if we use a fixed color could be `lightgrey` : 

![Test5](https://user-images.githubusercontent.com/31687635/79767787-21f83080-832a-11ea-8f3f-0344256d736d.gif)

**Comment by Skylsmoi** [comment]
thanks !

I think I would go for the grey hover. Event maybe with a 0.9 opacity, or a lighter gray.
I think hovering with the primary color wasn't a good idea

@celiamgtt @lebouquetin Thoughts on that ?

**Comment by metzgegu** [comment]
I also prefer the fixed color solution, I tried with a lighter gray (which correspond to 0.7 opacity of the previous gray I used) :

![HoverTest](https://user-images.githubusercontent.com/31687635/79845345-2faac600-83bd-11ea-9d14-00f928dceac1.gif)

**Comment by celiamgtt** [comment]
The light grey solution is better (more readable). It could be lighter, the idea is just to have a visual animation when the user moves the mouse but is has to be subtle (maybe #e9ecef is enough).

**Comment by celiamgtt** [comment]
Actually, we should avoid using primary color as background color behind texts or as text color because this color can be modify by users. If users set the color black, or white, or flashy red, the interface isn't readable anymore.

**Comment by Skylsmoi** [comment]
Ideally, we will have something to check whether the primary color is light or dark and change the font accordingly.
But that's for later : (

**Comment by celiamgtt** [comment]
@metzgegu notices that #e9ecef is too blue, I advise him to test #e8e8e8 instead.

**Comment by metzgegu** [comment]
Description has been updated with current hover color (#e8e8e8)

**Comment by Skylsmoi** [comment]
We need to make a list of each places where a change takes place to validate to tests:
- workspace content list
- workspace content list inside an opened folder
- dashboard member list
- dashboard recent activity

list that isn't using the primary color as hover color but should be changed as well to match the new hover color
- admin workspace list
- admin member list
- app feature status dropdown

dropdown that uses the primary color as hover and can also be changed:
- workspace content, dropdown to create a content
- workspace content, button extended action
- workspace content folder, button create in folder
- header change language button
- header my account button
- header admin button

Update the list if you think of another one

**Comment by metzgegu** [comment]
I updated the PR to cover all these cases
Dropdown item have bootstrap property when there are clicked (e.g `:active`), the font color become white: 

![DropdownExample](https://user-images.githubusercontent.com/31687635/79952463-c4272e00-847a-11ea-9a89-2e034c7ffd4a.gif)

We could remove it (use the same color font) or use a other font color when it is clicked

**Comment by Skylsmoi** [comment]
It would be nice to have a clicked feeling though
I think you can set the background color to the primary color only when :active
so that you wont have to handle the color

**Comment by metzgegu** [comment]
I updated the PR with the solution suggested by @Skylsmoi, See: 

![PrimaryTest](https://user-images.githubusercontent.com/31687635/79969575-f7c18280-8491-11ea-8641-575bdbc762c8.gif)

**Comment by gbonaspetti** [comment]
Lists that still have some problem:
- Add a member (dashboard and advanced dashboard) is still using the primary color as hover.
- Set the role (advanced dashboard) is with a blue background when active.

**Comment by metzgegu** [comment]
Add a member in dashboard isn't a list item but a fixed button, a lot of buttons in Tracim still have a hover with the primary color, I don't know of it is necessary to change it, see the gif in issue description for example

**Comment by gbonaspetti** [comment]
> Add a member in dashboard isn't a list item but a fixed button, a lot of buttons in Tracim still have a hover with the primary color, I don't know of it is necessary to change it here, see the gif in issue description for example

Sorry, maybe I expressed myself badly, when you go to add a member a list of autocomplete appears, this list that still has problems.

**Comment by metzgegu** [comment]
My bad, I understood now, my PR is up to date with changes requested

**Comment by gbonaspetti** [comment]
Verified on branch (wait merge to close).
