### ISSUE TITLE
rename user.reset_password.validity param to something more explicit

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#970]
**Describe the bug**
user.reset_password.validity is not explicit enough, name should reflect whe need a duration.

**Comment by inkhey** [comment]
@lebouquetin user.reset_password.validity name was chosen to be similar than already existent user.auth_token.validity, who is used for user auth token feature (which is not yet used in tracim_v2 but used in tracimv1 for calendar).

**Comment by PhilippeAccorsi** [comment]
@inkhey @lebouquetin this issue is it still active? or it is corrected by recent refactoring?

**Comment by lebouquetin** [comment]
@PhilippeAccorsi This is still an issue.
@inkhey a good naming would be `user.reset_password.token_validity` or `user.reset_password.token.validity` or `user.reset_password_token.validity`.

**Comment by lebouquetin** [comment]
this issue is for 2.1

**Comment by PhilippeAccorsi** [comment]
New name is: user.reset_password.token_lifetime
Verified.
